"""Threat intelligence report generator."""
from __future__ import annotations

from datetime import date
from pathlib import Path
from typing import Any
from collections import Counter

import sys
sys.path.insert(0, str(Path(__file__).parent.parent))
from config import OUTPUT_DIR


def generate_markdown_report(
    cves: list[dict[str, Any]],
    poam_entries: list[dict[str, Any]],
    executive_summary: str,
    filename: str = "threat_report.md",
) -> Path:
    """Generate a markdown threat intelligence report."""
    output_path = OUTPUT_DIR / filename
    today = date.today().strftime("%d %B %Y")

    severity_counts = Counter(c.get("severity", "UNKNOWN") for c in cves)
    tactic_counts = Counter(p.get("MITRE_Tactic", "Unknown") for p in poam_entries)
    top_tactics = tactic_counts.most_common(5)

    # Sort CVEs by risk score descending
    sorted_cves = sorted(cves, key=lambda x: x.get("risk_score", 0), reverse=True)

    lines = [
        f"# CyberSentry Threat Intelligence Report",
        f"",
        f"**Generated:** {today}  ",
        f"**Classification:** TLP:WHITE  ",
        f"**Analyst:** CyberSentry AI (claude-sonnet-4-6)  ",
        f"",
        f"---",
        f"",
        f"## Executive Summary",
        f"",
        executive_summary,
        f"",
        f"---",
        f"",
        f"## Vulnerability Overview",
        f"",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total CVEs Analysed | {len(cves)} |",
        f"| Critical | {severity_counts.get('CRITICAL', 0)} |",
        f"| High | {severity_counts.get('HIGH', 0)} |",
        f"| Medium | {severity_counts.get('MEDIUM', 0)} |",
        f"| Low | {severity_counts.get('LOW', 0)} |",
        f"",
        f"## MITRE ATT&CK Tactic Distribution",
        f"",
        f"| Tactic | CVE Count |",
        f"|--------|-----------|",
    ]
    for tactic, count in top_tactics:
        lines.append(f"| {tactic} | {count} |")

    lines += [
        f"",
        f"---",
        f"",
        f"## Detailed CVE Analysis",
        f"",
    ]

    for cve in sorted_cves:
        risk_emoji = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🟢"}.get(
            cve.get("severity", ""), "⚪"
        )
        lines += [
            f"### {risk_emoji} {cve['cve_id']} — {cve.get('severity', 'UNKNOWN')} (CVSS {cve.get('cvss_score', 'N/A')})",
            f"",
            f"**Risk Score:** {cve.get('risk_score', 'N/A')}/100  ",
            f"**MITRE Tactic:** {cve.get('mitre_tactic', 'N/A')}  ",
            f"**MITRE Technique:** {cve.get('mitre_technique', 'N/A')}  ",
            f"**Affected Products:** {', '.join(cve.get('affected_products', []))}  ",
            f"",
            f"> {cve.get('description', '')}",
            f"",
        ]

    lines += [
        f"---",
        f"",
        f"## POAM Summary",
        f"",
        f"| CVE ID | Severity | MITRE Tactic | Risk Score | Due Date | Owner |",
        f"|--------|----------|--------------|------------|----------|-------|",
    ]
    for entry in sorted(poam_entries, key=lambda x: x.get("Risk_Score", 0), reverse=True):
        lines.append(
            f"| {entry['CVE_ID']} | {entry['Severity']} | {entry['MITRE_Tactic']} "
            f"| {entry['Risk_Score']} | {entry['Due_Date']} | {entry['Owner']} |"
        )

    lines += [
        f"",
        f"---",
        f"",
        f"*Report generated by CyberSentry — AI-powered threat intelligence platform.*  ",
        f"*Powered by Anthropic Claude claude-sonnet-4-6 and ChromaDB RAG.*",
    ]

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path
